name: Crawl inspireaanmerking.nl

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 0'


jobs:
  crawl-inspireaanmerking:
    name: Crawl
    runs-on: python:3.11.6-bookworm
    steps:
    - name: Check-out repository
      uses: actions/checkout@v2
      with:
        repository: jcdan3/devops
        token: ${{ secrets.GITHUB_TOKEN }}


    - name: Install deps and crawl
      run: |
        pip install -r requirements.txt
        python crawler.py inspireaanmerking.nl.csv
      shell: bash

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        committer_name: GitHub Actions
        committer_email: 41898282+github-actions[bot]@users.noreply.github.com
        add: inspireaanmerking.nl.csv
        message: 'update inspireaanmerking.nl.csv'
